version: '3'

envfiles:
  - .env

tasks:
  tests:
    cmds:
      - go test ./...

  build:
    cmds:
      - go build ./cmd/app/main.go

  cover:
    cmds:
      - go test -short -count=1 -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
      - rm coverage.out

  gen:
    cmds:
      - mockgen -source=internal/services/message.go -destination internal/services/mocks/message_mock.go
      - mockgen -source=internal/services/template.go -destination internal/services/mocks/template_mock.go
      - mockgen -source=internal/services/user.go -destination internal/services/mocks/user_mock.go

  ## task migrate-create --name my_name
  migrate-create:
    cmds:
      - migrate create -ext sql -dir internal/databases/migrations {{.name}}

  migrate-up:
    cmds:
      - migrate -path ./internal/databases/migrations -database ${DATABASE_URL}?sslmode=disable up

  migrate-fix:
    cmds:
      - migrate -path ./internal/databases/migrations -database -database ${DATABASE_URL}?sslmode=disable force {{.number}}